### ISSUE TITLE
Adding AMD support

### ISSUE THREAD

**Issue by xwisdom** [viljamis/feature.js#16]
Hello Viljamis,

How about using the following wrapper for FeatureJS so that it can be loaded as an AMD module?

``` javascript
(function (global, document,factory) {
    if (typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(factory);
    } else {
        // Browser globals
        global.feature = factory();
    }
}(window, document, function () {
    // ... Fearure JS code goes here...
    return feature;
}));
```

**Comment by jlmakes** [comment]
+1

Something like `gulp-wrap-umd` can easily automate this for distribution files.

**Comment by DioNNiS** [comment]
UMD support has been added: https://github.com/viljamis/feature.js/pull/26

**Comment by meowsus** [comment]
@DioNNiS would you mind updating your PR to resolve conflicts and to use `gulp-wrap-umd` instead, now that there is a gulpfile present in the repo? Integrating this into the build step would be preferable, in my opinion. I understand that #26 has been open for over 3 years now, so feel free to pitch this back over the fence and I can investigate further.

**Comment by meowsus** [comment]
I pulled a total 180 on you guys. @DioNNiS disregard my previous request. I had to add UMD support to the library to be able to ramp up Jest's test suite. Thanks for the suggestion!
