### ISSUE TITLE
Add to NPM

### ISSUE THREAD

**Issue by viljamis** [viljamis/feature.js#2]

**Comment by richardgorman** [comment]
Will it be possible to choose which features to detect and have only those checks added to the build?

**Comment by nblackburn** [comment]
@richardgorman Not yet but i have made that suggestion, see #3.

**Comment by viljamis** [comment]
@richardgorman @nblackburn I believe Modernizr does that already? My plan is not to build a Modernizr clone, but to keep this library always very minimal, under 1kb, and if something new is added, then something must be also removed.

For now at least I intend to keep this library as simple as possible without adding dependencies on either the client or the development side (not even for the build process for now). This might sound weird I guess, but I kind of wanted to go back to my roots with this project to make things fun again. Hope this makes some sense at least!

**Comment by epiloque** [comment]
:+1:

**Comment by viljamis** [comment]
Added to npm. You can now also install by running `npm install feature.js`
