### ISSUE TITLE
"Android" is always capital "A"

### ISSUE THREAD

**Issue by Paul-Browne** [viljamis/feature.js#20]
In the "old android" test the string "Android" might be "android" -can't recall which devices this occurred on, but a simple (A|a)ndroid should check for both. Great work btw👍

**Comment by Paul-Browne** [comment]
Title should be "Android" isn't always capital "A"

**Comment by ShirtlessKirk** [comment]
The regex uses the case insensitive operator...

**Comment by meowsus** [comment]
Seems like @ShirtlessKirk is right, [the test uses the insensitive operator](https://github.com/viljamis/feature.js/blob/master/feature.js#L46). If you run into this again feel free to resubmit or reopen this issue!
