### ISSUE TITLE
localStorage support check is ambiguous

### ISSUE THREAD

**Issue by ShirtlessKirk** [viljamis/feature.js#21]
The `localStorage` check is ambiguous as it includes unsupported as well as out of quota in normal browsing and the Safari "I'll fail you if you're in private browsing mode and try `.setItem`" tests in one. It will also pass a false positive if you try that same thing on Android/Chrome; you can set and remove all you like without error but nothing actually happened.

A better check would be to verify `localStorage` exists on `window` followed by whether you can successfully write and _read_ in a try ... catch block as `.removeItem` returns `undefined` regardless of if the key existed or not.

**Comment by amovah** [comment]
Hi, It's very good point, I will fix it in my own repository

**Comment by meowsus** [comment]
@ShirtlessKirk thanks for this. I'll investigate further.
