### ISSUE TITLE
Consider lowercase for all feature names

### ISSUE THREAD

**Issue by rymohr** [viljamis/feature.js#24]
Since these are simple object properties and the feature detection will fail silently if you use the wrong name, I'd suggest keeping the feature names as simple as possible. 

For instance, why `css3Dtransform` and not `css3DTransform`?

```
feature.async
feature.addeventlistener
feature.canvas
feature.classlist
feature.cors
feature.contextmenu
feature.css3dtransform
feature.csstransform
feature.csstransition
feature.defer
feature.devicemotion
feature.deviceorientation
feature.geolocation
feature.historyapi
feature.placeholder
feature.localstorage
feature.matchmedia
feature.pictureelement
feature.queryselectorall
feature.remunit
feature.serviceworker
feature.sizes
feature.srcset
feature.svg
feature.touch
feature.viewportunit
feature.webgl
```

**Comment by softwarespot** [comment]
:+1:

**Comment by meowsus** [comment]
Unless @viljamis feels otherwise, I think we'll keep the naming the same for now. I wouldn't mind reopening this discussion when development ramps up for the next major release, however.
