### ISSUE TITLE
Consider binding for create()

### ISSUE THREAD

**Issue by jbmonroe** [viljamis/feature.js#29]
Instead of

```
create : function (el) { return document.createElement(el); },
```

use

```
create : document.createElement.bind(document),
```

I infer that you're not doing IE8 support, and everything else supports Function#bind.  It's kind of a performance enhancement, but maybe not worth it.

**Comment by meowsus** [comment]
Though IE 8 isn't specifically called out in the README as a device that this library is tested against, it would make sense for a feature detection library to try to detect features in as many browsers as possible, no? I have an inkling that the performance boon here would be minimal, but feel free to prove me wrong with a benchmark test :)
