### ISSUE TITLE
Faster Canvas support detection

### ISSUE THREAD

**Issue by jbmonroe** [viljamis/feature.js#30]
```
canvas : function () { return !!window.HTMLCanvasElement; },
```

It's tons faster since it doesn't require the overhead of creating an element.

This also works:

```
canvas : function () { return !!window.CanvasRenderingContext2D; },
```

See http://stackoverflow.com/questions/2745432/best-way-to-detect-that-html5-canvas-is-not-supported

**Comment by meowsus** [comment]
Thanks for the suggestion, @jbmonroe. I'll check it out!

**Comment by meowsus** [comment]
Ah! This method is already implemented! Closing.
