### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by Zubrik** [viljamis/feature.js#31]
This project is very interesting. It would be good to have it as a bower package.

Thanks.

**Comment by knagurski** [comment]
+1 for me. I just went to include it in a project and was a bit surprised it wasn't there.

**Comment by storypixel** [comment]
agree

**Comment by ianrose** [comment]
This doesn't directly solve the issue but I hope it's helpful for those who would like to manage this great project via Bower.

Install by specifying the Git endpoint:
```bash
$ bower install https://github.com/viljamis/feature.js.git#1.0.1 --save-dev
```

Which would update your `bower.json` like:

```json
{
  "name": "app-name",
  "version": "0.1.0",
  "devDependencies": {
    "feature.js": "https://github.com/viljamis/feature.js.git#1.0.1"
  },
  "private": true
}
```

**Comment by knagurski** [comment]
Actually, installing via bower is pretty easy.

    $ bower install feature.js --save-dev

**Comment by meowsus** [comment]
Closing, as this library is in the [Bower package index](https://bower.io/search/?q=feature.js).
