### ISSUE TITLE
websocket support?

### ISSUE THREAD

**Issue by stableShip** [viljamis/feature.js#34]
how can I check the websocket support? Is there going to add this feature? or there is some way I can easy to check?

**Comment by dannycroft** [comment]
Currently `feature.js` doesn't support WebSocket detection. You could simply
add it if you wanted in your own fork. Following the same pattern that this library has:

```javascript
webSocket: ("WebSocket" in window || "MozWebSocket" in window),
```

or something a little further:
```javascript
webSocket: (function() {
  if ("WebSocket" in window || "MozWebSocket" in window) {
    var protocol = 'https:' == location.protocol ? 'wss' : 'ws';
    try {
      return !!(new WebSocket(protocol + '://.').binaryType);
    } catch (e) {}
  }
  return false;
})(),
```

You could also use a specific WebSocket library to help with all the browser quirks you are most definitely going to encounter. Here is a fairly comprehensive list: https://ajf.me/websocket/#libs
