### ISSUE TITLE
No mention of browser support?

### ISSUE THREAD

**Issue by domfee** [viljamis/feature.js#35]
Hi, Whats the browser support like?

**Comment by viljamis** [comment]
@domfee The library is meant for feature testing so I've basically built it so that it supports all/most of the  browser/device combinations out there. 

It's been tested on for example IE 6.0+, iOS 3.0+, Android 1.6+, etc.

**Comment by domfee** [comment]
@viljamis Awesome:) Great Lib :)

**Comment by viljamis** [comment]
Added mention to the readme now!
