### ISSUE TITLE
Would using getters make it faster?

### ISSUE THREAD

**Issue by eorroe** [viljamis/feature.js#39]
I know the file is small and should be fast, perhaps I'm micro optimizing but Instead of running all the code right away would using getters make it faster, therefore only when each feature is checked:

```JS
if(feature.webGL) { // right here it'll run the getter instead of onload

}
```

**Perhaps only do this if this file exceeds a certain file size?**

**Comment by amovah** [comment]
we have a lot conversation about it here, #4

**Comment by eorroe** [comment]
Just replied
