### ISSUE TITLE
comma or semi-colon?

### ISSUE THREAD

**Issue by alainEHV** [viljamis/feature.js#40]
Currently, you have this code in the 'pfx' function:

```
var ucProp = prop.charAt(0).toUpperCase() + prop.substr(1),
  props = (prop + " " + prefixes.join(ucProp + " ") + ucProp).split(" ");
  memory[prop] = null;
```

Shouldn't the second line end with a comma, instead of a semi-colon?
Either that, or the indentation on line three is incorrect.

I would expect the indentation is off, since you're declaring the 'memory' Object a few line higher up in the 'pfx' function.

**Comment by meowsus** [comment]
Yeah, that looks like an indentation issue for sure. Thanks for the catch, @alainEHV!
