### ISSUE TITLE
Check for window to support Isomorphic JS

### ISSUE THREAD

**Issue by jljorgenson18** [viljamis/feature.js#42]
First off, great library

Although supporting isomorphic Javascript doesn't seem necessary at all, it would be nice if there was a conditional check for the window element. When doing server side rendering, an exception is throw when pulling in feature.js from node

```
}(window, document));
  ^

ReferenceError: window is not defined
```

Perhaps an empty object could be returned.

**Comment by softwarespot** [comment]
Or this?

**Comment by jljorgenson18** [comment]
So I didn't realize a few things initially. One is that requiring feature.js doesn't return an object. Rather, it sets all of the feature flags as globals. It may be beneficial to do the isomorphic check for common.js and amd, then return a feature object instead of putting all of the features flags as a global. This would help with greater compatibility. Here is an example from is.js

```javascript

(function(root, factory) {
    if(typeof define === 'function' && define.amd) {
        // AMD. Register as an anonymous module.
        define(function() {
            // Also create a global in case some scripts
            // that are loaded still are looking for
            // a global even when an AMD loader is in use.
            return (root.is = factory());
        });
    } else if(typeof exports === 'object') {
        // Node. Does not work with strict CommonJS, but
        // only CommonJS-like enviroments that support module.exports,
        // like Node.
        module.exports = factory();
    } else {
        // Browser globals (root is window)
        root.is = factory();
    }
} (this, function() {

```

**Comment by meowsus** [comment]
@jljorgenson18 I'm assuming that [this issue](https://github.com/viljamis/feature.js/issues/16) will resolve your and @softwarespot's problems. I'll close this issue, but be sure to reopen if you think I've missed something in what you're saying!
