### ISSUE TITLE
Is this repository still maintained?

### ISSUE THREAD

**Issue by meowsus** [viljamis/feature.js#55]
If not, I wouldn't mind becoming the maintainer.

**Comment by SmolinPavel** [comment]
@meowsus sounds like a good question..

**Comment by JakeBeresford** [comment]
Very generous of you to offer @meowsus - It'd be wonderful to have this repo maintained!

**Comment by tubbo** [comment]
![applause](https://media.wired.com/photos/5c5dd6da4d633a24e4d6b0e6/master/pass/Culture_InternetWeek_PelosiClap-1094200504.jpg)

**Comment by meowsus** [comment]
Thanks @viljamis, looking forward to working with you!
