### ISSUE TITLE
Directly Object

### ISSUE THREAD

**Issue by amovah** [viljamis/feature.js#7]
I think Feature function constructor is useless, we should use the Feature Object directly. It can improve the performance of Feature
a little of code:

```javascript
Feature = {
    css3Dtransform : (function() {
      var test = (!util.old && util.pfx("perspective") !== null);
      return !!test;
    })()
}
```

and Why should we have the constructor that does nothing?

and I'm interested in fixing this issue.

**Comment by viljamis** [comment]
@amovah This is a good point and might make the library slightly smaller too. Do you want to help achieving this?

**Comment by amovah** [comment]
Yes, Of course. please assign me and I'll will fix this

**Comment by viljamis** [comment]
@amovah Can you please fork this repository and make a pull request (I can’t assign you here directly)?

**Comment by amovah** [comment]
I've just forked.

**Comment by viljamis** [comment]
This is now merged and fixed!
